version: "test"

services:
  namenode:
    image: sandbox/hadoop:latest
    hostname: namenode
    container_name: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
      - 8020:8020 # required to acces hdfs from the host
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/opt/hadoop/dfs/name" # required to set cluster id with ENSURE_NAMENODE_CLUSTERID
      # ENSURE_NAMENODE_DIR: "enforce-format" # use ONLY when CREATING container's volumes, will format namenode
      ENSURE_NAMENODE_CLUSTERID: "sandbox" # ensures that datanodes will join previously joined cluster
    volumes:
      - namenode:/opt/hadoop/dfs/name

  datanode:
    image: sandbox/hadoop:latest
    hostname: localhost
    container_name: datanode
    command: ["hdfs", "datanode"]
    ports:
      - 9864:9864
    env_file:
      - ./config
    volumes:
      - datanode:/opt/hadoop/dfs/data

  resourcemanager:
    image: sandbox/hadoop:latest
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./scripts:/opt/hadoop/scripts
      - ./samples:/opt/hadoop/samples

  nodemanager:
    image: sandbox/hadoop:latest
    hostname: nodemanager
    container_name: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  timelineserver:
    image: sandbox/hadoop:latest
    hostname: timelineserver
    container_name: timelineserver
    command: ["yarn", "timelineserver"]
    env_file:
      - ./config
    volumes:
      - timelineserver:/opt/hadoop/yarn/timeline

volumes:
  namenode:
  datanode:
  timelineserver: