version: "test"

services:
  namenode:
    build: .
    hostname: namenode
    container_name: namenode
    command: ["hdfs", "namenode"]
    ports:
      - 9870:9870
    env_file:
      - ./config
    environment:
      ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

  datanode-one:
    build: .
    container_name: datanode-one
    command: ["hdfs", "datanode"]
    env_file:
      - ./config

  datanode-two:
    build: .
    container_name: datanode-two
    command: ["hdfs", "datanode"]
    env_file:
      - ./config

  resourcemanager:
    build: .
    hostname: resourcemanager
    container_name: resourcemanager
    command: ["yarn", "resourcemanager"]
    ports:
      - 8088:8088
    env_file:
      - ./config
    volumes:
      - ./test.sh:/opt/test.sh

  nodemanager:
    build: .
    hostname: nodemanager
    container_name: nodemanager
    command: ["yarn", "nodemanager"]
    env_file:
      - ./config

  timelineserver:
    build: .
    hostname: timelineserver
    container_name: timelineserver
    command: ["yarn", "timelineserver"]
    env_file:
      - ./config