version: "sandbox"

services:
   namenode:
      image: apache/hadoop:3.3.5
      hostname: namenode
      command: ["hdfs", "namenode"]
      ports:
        - 9870:9870
      env_file:
        - ./container.env
      environment:
          ENSURE_NAMENODE_DIR: "/tmp/hadoop-root/dfs/name"

   datanode:
      image: apache/hadoop:3.3.5
      command: ["hdfs", "datanode"]
      env_file:
        - ./container.env

   resourcemanager:
      image: apache/hadoop:3.3.5
      hostname: resourcemanager
      command: ["yarn", "resourcemanager"]
      ports:
         - 8088:8088
      env_file:
        - ./container.env
      volumes:
        - ./test.sh:/opt/test.sh

   nodemanager:
      image: apache/hadoop:3.3.5
      command: ["yarn", "nodemanager"]
      env_file:
        - ./container.env

volumes:
    namenode:
    datanode: