version: "sandbox"

# used to test the zookeeper cluster

services:
  zoo-one:
    image: zookeeper:latest
    restart: unless-stopped
    hostname: zoo-one
    container_name: zoo-one
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
      - 8080:8080
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo-one:2888:3888;2181 server.2=zoo-two:2888:3888;2181 server.3=zoo-three:2888:3888;2181
    volumes:
      - zoo-one-data:/data
      - zoo-one-datalog:/datalog
      - zoo-one-logs:/logs

  zoo-two:
    image: zookeeper:latest
    restart: unless-stopped
    hostname: zoo-two
    container_name: zoo-two
    ports:
      - 2182:2181
      - 2889:2888
      - 3889:3888
      - 8081:8080
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo-one:2888:3888;2181 server.2=zoo-two:2888:3888;2181 server.3=zoo-three:2888:3888;2181
    volumes:
      - zoo-two-data:/data
      - zoo-two-datalog:/datalog
      - zoo-two-logs:/logs

  zoo-three:
    image: zookeeper:latest
    restart: unless-stopped
    hostname: zoo-three
    container_name: zoo-three
    ports:
      - 2183:2181
      - 2890:2888
      - 3890:3888
      - 8082:8080
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo-one:2888:3888;2181 server.2=zoo-two:2888:3888;2181 server.3=zoo-three:2888:3888;2181
    volumes:
      - zoo-three-data:/data
      - zoo-three-datalog:/datalog
      - zoo-three-logs:/logs

volumes:
  zoo-one-data:
  zoo-one-datalog:
  zoo-one-logs:
  zoo-two-data:
  zoo-two-datalog:
  zoo-two-logs:
  zoo-three-data:
  zoo-three-datalog:
  zoo-three-logs: